export const IS_DATA_LOADING = "IS_DATA_LOADING";

//
export const INITIALIZE_PRODUCTS = "INITIALIZE_PRODUCTS";
export const INITIALIZE_CATEGORIES = "INITIALIZE_CATEGORIES";

//
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const MOVE_TO_CART = "MOVE_TO_CART";

//
export const FILTER_BY_CATEGORIES = "FILTER_BY_CATEGORIES";
export const FILTER_BY_PRODUCT_TYPE = "FILTER_BY_PRODUCT_TYPE";
export const FILTER_BY_PRICE_RANGE = "FILTER_BY_PRICE_RANGE";
export const FILTER_SORT_BY_PRICE = "FILTER_SORT_BY_PRICE";
export const FILTER_BY_STOCK = "FILTER_BY_STOCK";
export const FILTER_BY_DELIVERY = "FILTER_BY_DELIVERY";
export const FILTER_BY_RATING = "FILTER_BY_RATING";
export const CLEAR_FILTER = "CLEAR_FILTER";
